### ISSUE TITLE
missing start_date for memberships

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/scraper-sk_nrsr#3]
There are no start dates for some memberships, e.g., 
http://api.parldata.eu/sk/nrsr/memberships/54d2a87f273a394ad5dbc878

**Comment by girogiro** [comment]
Start date and end date of a membership are set in the data only if explicitly present on the source web. They are not inferred from founding date and dissolution date of the respective organization because they may differ and yet not be specified on the source web. The reasoning is: rather provide less data than incorrect data. An application using the data from API may choose to use dates of the organization in case of missing dates of the membership.
